# Generated by Django 3.0.8 on 2020-08-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Lane_name',
        ),
        migrations.AddField(
            model_name='post',
            name='WasteIn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='WasteOut',
            field=models.IntegerField(default=0),
        ),
    ]
